language: ruby
cache: bundler

rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - ruby-head
  - jruby-9.2.11.1
  - jruby-9.0.5.0
  - jruby-head
  - truffleruby

matrix:
  include:
    - rvm: 2.5
      name: "Run Danger and Code Climate"
      before_script:
        - bundle exec danger
      after_script:
        - bundle exec codeclimate-test-reporter
    - rvm: 2.5
      name: "Integration Tests"
      install:
        - for dir in spec/integration/*; do BUNDLE_GEMFILE=$dir/Gemfile bundle; done
      script:
        - set -e ; for dir in spec/integration/*; do BUNDLE_GEMFILE=$dir/Gemfile bundle exec rspec $dir; done
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
