language: ruby
sudo: false

rvm:
  - 2.2.1
  - 2.1.2
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2.2.10
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.2.1 # https://github.com/intridea/hashie/pull/285
