name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: [ '2.1.x', '2.2.x', '2.3.x', '2.4.x', '2.5.x', '2.6.x']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build and test with Rake
      env:
        CI: 'true'
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v1
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes
